In [30]:
import pandas as pd
s = pd.Series([10, 20, 30, 40, 50], index=['a','b','c','d','e']) # creating series

print("Panda Series")
print (s)
print("/n Access Single vlaue ", s['c'])

Panda Series
a    10
b    20
c    30
d    40
e    50
dtype: int64
/n Access Single vlaue  30

In [ ]:
data = {
    'Name': ['Masterecard', 'Wipro', 'TCS'],
    'sal': [21, 20, 23],
    'rate': [4, 5, 4]
}

df = pd.DataFrame(data)                         #creating dataframe

print("Pandas DataFrame:")
print(df)                                       #printing data frame
print("\nAccess single column as series:")
print(df['sal'])
type(df)

Pandas DataFrame:
          Name  sal  rate
0  Masterecard   21     4
1        Wipro   20     5
2          TCS   23     4

Access single column as series:
0    21
1    20
2    23
Name: sal, dtype: int64

pandas.core.frame.DataFrame

In [10]:
#for information only
pd.read_csv("Salary_Data.csv")         # load CSV file
df.to_csv("output.csv", index=False)   # save to CSV

In [ ]:
import pandas as pd
df = pd.read_csv("Salary_Data.csv") # importing data
s = pd.Series(df['YearsExperience'].head().values, index=['a', 'b', 'c', 'd', 'e'])         # creating series
print("Pandas Series:")
print(s)                                                                #printing series

print("\nAccess single value:", s['c'])
print(s)
print("\nType of df:", type(df))

Pandas Series:
a    1.1
b    1.3
c    1.5
d    2.0
e    2.2
dtype: float64

Access single value: 1.5
a    1.1
b    1.3
c    1.5
d    2.0
e    2.2
dtype: float64

Type of df: <class 'pandas.core.frame.DataFrame'>

In [12]:
df['YearsExperience']             # select single column

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

In [13]:
df.iloc[0]             # first row by index
df.iloc[1:4]           # rows by index range
df.loc[df['YearsExperience']>5] # filter condition

    YearsExperience    Salary
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [14]:
df.head()        # first 5 rows

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [15]:
df.tail()        # last 5 rows

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [16]:
df.info()        # summary (data types, non-null count)
df.dtypes        # data types of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

YearsExperience    float64
Salary             float64
dtype: object

In [20]:
df.columns       # list of column names

Index(['YearsExperience', 'Salary'], dtype='object')

In [19]:
df.index         # row index

RangeIndex(start=0, stop=30, step=1)

In [22]:
df['YearsExperience'].mean()     # average marks

np.float64(5.3133333333333335)

In [23]:
df['YearsExperience'].median()   # median

np.float64(4.7)

In [25]:
df['YearsExperience'].max()      # maximum value

np.float64(10.5)

In [26]:
df['YearsExperience'].min()      # minimum value

np.float64(1.1)

In [27]:
df['YearsExperience'].sum()      # sum of column

np.float64(159.4)

In [28]:
df['YearsExperience'].value_counts()  # frequency count

YearsExperience
4.0     2
3.2     2
1.1     1
1.3     1
2.0     1
1.5     1
2.9     1
2.2     1
3.0     1
3.7     1
3.9     1
4.1     1
4.5     1
4.9     1
5.1     1
5.3     1
5.9     1
6.0     1
6.8     1
7.1     1
7.9     1
8.2     1
8.7     1
9.0     1
9.5     1
9.6     1
10.3    1
10.5    1
Name: count, dtype: int64